In [1]:
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

In [2]:
load_path ='/kaggle/input/competitions/titanic/train.csv'
hold_titanic_data = pd.read_csv(load_path)

In [3]:
hold_titanic_data.head()
hold_titanic_data.columns
hold_titanic_data.describe()
hold_titanic_data['Age']=hold_titanic_data['Age'].fillna(hold_titanic_data['Age'].median())
hold_titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
hold_titanic_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.019697,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
hold_titanic_data['Sex'] = hold_titanic_data['Sex'].map({"male" : 0, "female" : 1})
hold_titanic_data.describe()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,0.352413,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,0.477990,13.019697,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,0.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,1.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
y = hold_titanic_data.Survived

In [7]:
features = ['Pclass' , 'SibSp' , 'Parch' , 'Fare' , 'Sex' , 'Age']
X = hold_titanic_data[features]

In [8]:
train_X , val_X , train_y , val_y = train_test_split(X , y ,random_state=1)
titanic_model = RandomForestClassifier(random_state=1)
titanic_model.fit(train_X , train_y)

RandomForestClassifier(random_state=1)

In [9]:
titanic_predict = titanic_model.predict(val_X)
mae = mean_absolute_error(titanic_predict , val_y)
print(mae)
#MAE is 0.26 — this makes sense for a classification problem. It means model is wrong about 26% of the time on survival predictions.

0.22869955156950672

In [10]:
titanic_final_model = RandomForestClassifier(random_state = 1)
titanic_final_model.fit( X , y)

RandomForestClassifier(random_state=1)

In [11]:
load_path2 = '/kaggle/input/competitions/titanic/test.csv'
hold_titanic_data2 = pd.read_csv(load_path2)

In [12]:
hold_titanic_data2['Age']=hold_titanic_data2['Age'].fillna(hold_titanic_data2['Age'].median())
hold_titanic_data2['Sex'] = hold_titanic_data2['Sex'].map({"male" : 0, "female" : 1})

In [13]:
Z = hold_titanic_data2[features]

In [14]:
predictions = titanic_final_model.predict(Z)

In [15]:
output = pd.DataFrame({'PassengerId': hold_titanic_data2.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)